#pragma once

#define ForOpenGLFunctions(_do) \
    _do(PFNGLDEBUGMESSAGECALLBACKPROC,      glDebugMessageCallback)      \
    _do(PFNGLCREATESHADERPROC,              glCreateShader)              \
    _do(PFNGLDELETESHADERPROC,              glDeleteShader)              \
    _do(PFNGLSHADERSOURCEPROC,              glShaderSource)              \
    _do(PFNGLCOMPILESHADERPROC,             glCompileShader)             \
    _do(PFNGLGETSHADERIVPROC,               glGetShaderiv)               \
    _do(PFNGLGETSHADERINFOLOGPROC,          glGetShaderInfoLog)          \
    _do(PFNGLCREATEPROGRAMPROC,             glCreateProgram)             \
    _do(PFNGLDELETEPROGRAMPROC,             glDeleteProgram)             \
    _do(PFNGLATTACHSHADERPROC,              glAttachShader)              \
    _do(PFNGLLINKPROGRAMPROC,               glLinkProgram)               \
    _do(PFNGLGETPROGRAMIVPROC,              glGetProgramiv)              \
    _do(PFNGLGETPROGRAMINFOLOGPROC,         glGetProgramInfoLog)         \
    _do(PFNGLUSEPROGRAMPROC,                glUseProgram)                \
    _do(PFNGLGETUNIFORMLOCATIONPROC,        glGetUniformLocation)        \
    _do(PFNGLUNIFORM1IVPROC,                glUniform1iv)                \
    _do(PFNGLCREATEBUFFERSPROC,             glCreateBuffers)             \
    _do(PFNGLDELETEBUFFERSPROC,             glDeleteBuffers)             \
    _do(PFNGLNAMEDBUFFERDATAPROC,           glNamedBufferData)           \
    _do(PFNGLNAMEDBUFFERSUBDATAPROC,        glNamedBufferSubData)        \
    _do(PFNGLCREATEVERTEXARRAYSPROC,        glCreateVertexArrays)        \
    _do(PFNGLDELETEVERTEXARRAYSPROC,        glDeleteVertexArrays)        \
    _do(PFNGLVERTEXARRAYELEMENTBUFFERPROC,  glVertexArrayElementBuffer)  \
    _do(PFNGLVERTEXARRAYVERTEXBUFFERPROC,   glVertexArrayVertexBuffer)   \
    _do(PFNGLENABLEVERTEXARRAYATTRIBPROC,   glEnableVertexArrayAttrib)   \
    _do(PFNGLVERTEXARRAYATTRIBFORMATPROC,   glVertexArrayAttribFormat)   \
    _do(PFNGLVERTEXARRAYATTRIBIFORMATPROC,  glVertexArrayAttribIFormat)  \
    _do(PFNGLVERTEXARRAYATTRIBBINDINGPROC,  glVertexArrayAttribBinding)  \
    _do(PFNGLVERTEXARRAYBINDINGDIVISORPROC, glVertexArrayBindingDivisor) \
    _do(PFNGLBINDVERTEXARRAYPROC,           glBindVertexArray)           \
    _do(PFNGLBINDBUFFERBASEPROC,            glBindBufferBase)            \
    _do(PFNGLCREATETEXTURESPROC,            glCreateTextures)            \
    _do(PFNGLTEXTURESTORAGE2DPROC,          glTextureStorage2D)          \
    _do(PFNGLTEXTURESUBIMAGE2DPROC,         glTextureSubImage2D)         \
    _do(PFNGLTEXTUREPARAMETERIPROC,         glTextureParameteri)         \
    _do(PFNGLBINDTEXTUREUNITPROC,           glBindTextureUnit)           \
    _do(PFNGLCREATEFRAMEBUFFERSPROC,        glCreateFramebuffers)        \
    _do(PFNGLDELETEFRAMEBUFFERSPROC,        glDeleteFramebuffers)        \
    _do(PFNGLBINDFRAMEBUFFERPROC,           glBindFramebuffer)           \
    _do(PFNGLTEXIMAGE2DMULTISAMPLEPROC,     glTexImage2DMultisample)     \
    _do(PFNGLFRAMEBUFFERTEXTURE2DPROC,      glFramebufferTexture2D)      \
    _do(PFNGLTEXSTORAGE2DPROC,              glTexStorage2D)              \
    _do(PFNGLDRAWBUFFERSPROC,               glDrawBuffers)               \
    _do(PFNGLCLEARTEXIMAGEPROC,             glClearTexImage)             \
    _do(PFNGLCLEARBUFFERFVPROC,             glClearBufferfv)             \